### ISSUE TITLE
Raspberry Pi Installation

### ISSUE THREAD

**Issue by aramperez** [maximkulkin/lewansoul-lx16a#3]
It appears that on a RasPi you need to install with the sudo command. But you still get an error concerning the PyQt5 files:
Traceback (most recent call last):
  File "/usr/local/bin/lewansoul_lx16a_terminal", line 4, in <module>
    __import__('pkg_resources').run_script('lewansoul-lx16a-terminal==0.1', 'lewansoul_lx16a_terminal')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PyQt5' distribution was not found and is required by lewansoul-lx16a-terminal

I've tried installing the PyQt5 package with Preferences->Add/Remove Software but I still get an error.

**Comment by 1scai** [comment]
> 
> 
> I'll try to do that but I do not know Python that well. Thanks!

aramperez did you figure out how to control the arm with the pi? I'm having the same issue. Thanks.

**Comment by aramperez** [comment]
Sorry, that was more than 1 year ago. I was able install the package and can communicate with the servos. However, I ended up writing my own library in C++ based on the request from my client.

**Comment by BerGar92** [comment]
Hi, it's been a while since this thread was messaged but I'm trying to work with these servos myself and am currently struggling to interact with them other than the desktop software for individual servo control/debug. You say you created your own C++ library for them few questions, first is it possible to get that library? second did you end up running it on a RP or for use with Arduino like I have seen in some of your other projects? finally did you manage to get full functionality out of them with every command which is programmed into them?

**Comment by aramperez** [comment]
Hi BerGar92, I'll have to ask my client if he wants to open source the library. It runs on a RP but should be adaptable to an Arduino. I haven't look at the library is quite a while but IIRC, it had most of the functionality. It shouldn't be hard to add any missing functionality.
